package com.mitrais.ayr.screen;

import com.mitrais.ayr.dto.DataPayload;
import com.mitrais.ayr.dto.FundTransferDto;
import com.mitrais.ayr.model.view.Component;
import com.mitrais.ayr.model.view.Screen;
import com.mitrais.ayr.model.view.util.EnumViewUtil;
import com.mitrais.ayr.model.view.util.ScreenGenerator;
import com.mitrais.ayr.model.view.util.Workflow;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;

import static com.mitrais.ayr.model.view.util.EnumViewUtil.ComponentType.FORM;

public class FundTransferInqScreen extends UIAdapter {
    @Override
    public Screen construct() {
        Screen sc = new Screen();
        sc.setScreenId("21");
        sc.setScreenName("Fund Transfer Inq Screen");
        Component destAcct = new Component("21", FORM, "Please enter destination account and press enter to continue or \n" +
                "press enter to go back to Transaction: ", "", null, null);
        Component amount = new Component("22", FORM, "Please enter transfer amount and \n" +
                "press enter to continue or \n" +
                "press enter to go back to Transaction: ", null, null, null);
        Component refNumber = new Component("23", FORM, "Reference Number: (This is an autogenerated random 6 digits number)\n" +
                "press enter to continue", "uuid", null, null);

        List<Component> lc = new ArrayList<>();
        lc.add(destAcct);
        lc.add(amount);
        lc.add(refNumber);
        sc.setComponent(lc);
        return sc;

    }

    @Override
    public void notify(List<DataPayload> data) {

        FundTransferDto dto = new FundTransferDto();

        dto.setDestAcct(data.get(0).getValue());
        dto.setAmount(new BigDecimal(data.get(1).getValue()));
        dto.setRefNo(data.get(2).getValue());
        FundTransferConf nextPage = new FundTransferConf(dto);
        new ScreenGenerator(nextPage).generate();

    }
}
